from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, JSON, ForeignKey, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class RiskScore(Base):
    """Predictive maintenance risk scores per server (0-100, higher = worse)."""
    __tablename__ = "risk_scores"

    id = Column(String(36), primary_key=True)
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), nullable=False, index=True)
    scored_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    overall_risk = Column(Float, nullable=False)
    risk_level = Column(String(16), nullable=False)  # low | medium | high

    disk_risk = Column(Float)
    psu_risk = Column(Float)
    fan_risk = Column(Float)
    memory_risk = Column(Float)
    thermal_risk = Column(Float)

    factors = Column(JSON)  # [{"component": "disk", "reason": "...", "points": 30}]

    server = relationship("Server", back_populates="risk_scores")

    __table_args__ = (Index("ix_risk_server_time", "server_id", "scored_at"),)


class Recommendation(Base):
    """Actionable recommendations generated by the intelligence engines."""
    __tablename__ = "recommendations"

    id = Column(String(36), primary_key=True)
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), index=True)

    category = Column(String(48), nullable=False, index=True)  # optimization|firmware|lifecycle|maintenance|thermal|power
    severity = Column(String(16), nullable=False)              # info|warning|critical
    title = Column(String(255), nullable=False)
    body = Column(String(1024), nullable=False)
    rationale = Column(String(1024))
    steps = Column(JSON)  # list of numbered remediation steps

    dismissed = Column(Boolean, default=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    server = relationship("Server", back_populates="recommendations")

    __table_args__ = (Index("ix_reco_active", "dismissed", "severity"),)


class AvailabilityRecord(Base):
    """Daily uptime rollups per server for SLA reporting."""
    __tablename__ = "availability_records"

    id = Column(String(36), primary_key=True)
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), nullable=False, index=True)
    date = Column(DateTime(timezone=True), nullable=False, index=True)

    uptime_seconds = Column(Integer, default=0)
    downtime_seconds = Column(Integer, default=0)
    state_changes = Column(Integer, default=0)
    uptime_pct = Column(Float)

    server = relationship("Server", back_populates="availability_records")

    __table_args__ = (Index("ix_avail_server_date", "server_id", "date"),)


class ChangeEvent(Base):
    """Transition log: status/power/drift changes per server (for the Changelog feed)."""
    __tablename__ = "change_events"

    id = Column(String(36), primary_key=True)
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), index=True)
    hostname = Column(String(255), index=True)  # denormalized for fast display
    kind = Column(String(16), nullable=False, index=True)  # status | power | drift
    old_value = Column(String(32))
    new_value = Column(String(32))
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    __table_args__ = (
        Index("ix_change_created", "created_at"),
        Index("ix_change_kind_created", "kind", "created_at"),
    )


class TriageLog(Base):
    """Autonomous SEL-triage audit trail: one row per triaged SEL event.

    Doubles as the dedup key (event_key) so each SEL event is triaged once, and as
    the human-reviewable record of what the AI decided and whether it acted (or, in
    shadow mode, what it WOULD have done)."""
    __tablename__ = "triage_logs"

    id = Column(String(36), primary_key=True)
    event_key = Column(String(255), nullable=False, unique=True, index=True)  # dedup: host|sel_id|ts
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), index=True)
    hostname = Column(String(255), index=True)
    severity = Column(String(16))                 # Critical | Warning | Info (from SEL)
    message = Column(String(1024))                # the SEL event text
    verdict = Column(String(16), index=True)      # noise | hardware_issue | needs_review
    confidence = Column(Float)                    # 0-1 from the agent
    reasoning = Column(String(2048))              # short AI explanation
    action_taken = Column(String(32))             # none | acknowledged | alert_created | shadow
    shadow = Column(Boolean, default=True)        # True = no real action was taken
    alert_id = Column(String(36))                 # FK-ish link if an alert was raised
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    __table_args__ = (
        Index("ix_triage_created", "created_at"),
        Index("ix_triage_verdict_created", "verdict", "created_at"),
    )


class BiosHistory(Base):
    """BIOS config A/B history: a 'baseline' row (BIOS+microcode BEFORE a flash) and a
    'patch' row (AFTER the post-flash refresh) per server. Powers the Compliance tab's
    Baseline-vs-Patch comparison and the tuning before/after audit."""
    __tablename__ = "bios_history"

    id = Column(String(36), primary_key=True)
    server_id = Column(String(36), ForeignKey("servers.id", ondelete="CASCADE"), index=True)
    hostname = Column(String(255), index=True)
    phase = Column(String(16), index=True)        # baseline | patch
    bios_version = Column(String(64))
    microcode = Column(String(32))
    bmc_firmware = Column(String(64))
    attributes = Column(JSON)                      # optional tuning before/after snapshot
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    __table_args__ = (
        Index("ix_bios_hist_server_phase", "server_id", "phase", "created_at"),
    )
